services:
  pickmypostcode-checker:
    image: jonathanlangton1/pickmypostcode-auto-win-checker:latest
    container_name: pickmypostcode-checker
    env_file: .env
    environment:
      - TZ=Europe/London
    volumes:
      - ./pickmypostcode_logs:/app/logs
    working_dir: /app
    restart: on-failure:3
